language: node_js
sudo: false
node_js:
  - "5.4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_install:
  - echo "Testing My project"
install:
  - npm install
script:
  - npm run unit