language: node_js
sudo: false
node_js:
  - "4.0"
install:
  - npm install
script:
  - npm run unit
dist: trusty
addons:
  chrome: stable
before_install:
- npm i -g npm@4.1
cache:
  directories:
    - "node_modules"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start